#!/bin/env zsh
# __          ___ _   _______          _
# \ \        / (_) | |__   __|        | |
#  \ \  /\  / / _| |    | | __ _ _   _| | ___  _ __
#   \ \/  \/ / | | |    | |/ _` | | | | |/ _ \| '__|
#    \  /\  /  | | |    | | (_| | |_| | | (_) | |
#     \/  \/   |_|_|    |_|\__,_|\__, |_|\___/|_|
#                                 __/ |
#                                |___/
# Web: https://wil.dev
# Github: https://github.com/wiltaylor
# Contact: web@wiltaylor.dev
# Feel free to use this configuration as you wish.

push-org(){
	rclone sync ~/trashbox/org Trashbox:/org
}

pull-org(){
	rclone sync Trashbox:/org ~/trashbox/org
}

push-trashbox(){
	rclone sync ~/trashbox/ Trashbox:/
}

pull-trashbox(){
	rclone sync Trashbox:/ ~/trashbox/
}
