# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0d20ff14-1f0a-45eb-aae6-22bd288da254";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/d909a411-411f-4f7d-888c-3d4254e1d542";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/0d20ff14-1f0a-45eb-aae6-22bd288da254";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/0d20ff14-1f0a-45eb-aae6-22bd288da254";
      fsType = "btrfs";
      options = [ "subvol=@var" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/0d20ff14-1f0a-45eb-aae6-22bd288da254";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/.pagefile" =
    { device = "/dev/disk/by-uuid/0d20ff14-1f0a-45eb-aae6-22bd288da254";
      fsType = "btrfs";
      options = [ "subvol=@pagefile" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5842-CFF5";
      fsType = "vfat";
    };

    swapDevices = [ 
      {
        device = "/.pagefile/pagefile";
        size = 2048;
      }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
