#! /bin/bash
# __          ___ _   _______          _            
# \ \        / (_) | |__   __|        | |           
#  \ \  /\  / / _| |    | | __ _ _   _| | ___  _ __ 
#   \ \/  \/ / | | |    | |/ _` | | | | |/ _ \| '__|
#    \  /\  /  | | |    | | (_| | |_| | | (_) | |   
#     \/  \/   |_|_|    |_|\__,_|\__, |_|\___/|_|   
#                                 __/ |             
#                                |___/              
# Web: https://wil.dev
# Github: https://github.com/wiltaylor
# Contact: web@wiltaylor.dev
# Feel free to use this configuration as you wish.

sxhkd &
feh --bg-scale ~/.config/bspwm/wall.jpg &
~/.config/polybar/launch.sh & 
picom &

bspc config focus_follows_pointer true

bspc monitor DP-0 -d 1 2 3
bspc monitor DP-2 -d 4 5 6
bspc monitor DP-4 -d 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
