#!/run/current-system/sw/bin/bash
mkdir /mnt/sysinstall -p

parted $1 mklabel gpt
parted $1 mkpart "NIXBOOT" fat32 1MiB 261Mib
parted $1 set 1 esp on
parted $1 mkpart "NIXCRYPTROOT" ext4 261Mib 100%

cryptsetup luksFormat ${1}p2
cryptsetup open ${1}p2 nixcryptroot

mkfs.btrfs /dev/mapper/nixcryptroot
mkfs.fat -F32 ${1}p1

mount /dev/mapper/nixcryptroot /mnt/sysinstall
btrfs su cr /mnt/sysinstall/@
btrfs su cr /mnt/sysinstall/@home
btrfs su cr /mnt/sysinstall/@var
btrfs su cr /mnt/sysinstall/@snapshots
btrfs su cr /mnt/sysinstall/@pagefiles
umount /mnt/sysinstall

mount -o noatime,compress=lzo,space_cache,subvol=@ /dev/mapper/nixcryptroot /mnt/sysinstall
mkdir -p /mnt/sysinstall/{boot,home,var,.snapshots,.pagefiles}
mount -o noatime,compress=lzo,space_cache,subvol=@home /dev/mapper/nixcryptroot /mnt/sysinstall/home
mount -o noatime,compress=lzo,space_cache,subvol=@var /dev/mapper/nixcryptroot /mnt/sysinstall/var
mount -o noatime,compress=lzo,space_cache,subvol=@snapshots /dev/mapper/nixcryptroot /mnt/sysinstall/.snapshots
mount -o noatime,compress=lzo,space_cache,subvol=@pagefiles /dev/mapper/nixcryptroot /mnt/sysinstall/.pagefiles
mount ${1}p1 /mnt/sysinstall/boot

echo "Partitions created and mounted!"
